"""
Export utilities for saving analysis results.
Supports exporting to Markdown and plain text.
"""
import os
from datetime import datetime
from config import EXPORT_DIR


def export_analysis_markdown(data, roadmap, advice_list, difficulty_info, languages=None):
    """
    Export a single repository analysis as a Markdown file.
    Returns the file path on success, or None on failure.
    """
    os.makedirs(EXPORT_DIR, exist_ok=True)

    safe_name = data["repo_name"].replace("/", "_").replace(" ", "_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{safe_name}_{timestamp}.md"
    filepath = EXPORT_DIR / filename

    difficulty_name, score, _ = difficulty_info

    lines = [
        f"# 🔬 Repository Analysis: {data['repo_name']}",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**URL:** {data['url']}",
        "",
        "---",
        "",
        "##  Repository Information",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Owner** | {data['owner']} |",
        f"| **Repository** | {data['repo_name']} |",
        f"| **Description** | {data['description']} |",
        f"| **Primary Language** | {data.get('language', 'N/A')} |",
        f"| **Stars** |  {data['stars']:,} |",
        f"| **Forks** | 🍴 {data['forks']:,} |",
        f"| **Open Issues** |  {data.get('open_issues', 0):,} |",
        f"| **License** | {data.get('license', 'N/A')} |",
        f"| **Default Branch** | {data.get('default_branch', 'main')} |",
        f"| **Last Updated** | {data.get('updated_at', 'N/A')[:10]} |",
        f"| **Created** | {data.get('created_at', 'N/A')[:10]} |",
        "",
    ]

    # Topics
    topics = data.get("topics", [])
    if topics:
        lines.append("###  Topics")
        lines.append("")
        lines.append(", ".join(f"`{t}`" for t in topics))
        lines.append("")

    # Difficulty
    lines.extend([
        "##  Difficulty Assessment",
        "",
        f"**Level:** {difficulty_name} (Score: {score}/10)",
        "",
    ])

    # Languages
    if languages:
        total = sum(languages.values())
        lines.extend([
            "##  Languages Used",
            "",
            "| Language | Percentage |",
            "|----------|-----------|",
        ])
        for lang, bytes_count in sorted(languages.items(), key=lambda x: x[1], reverse=True):
            pct = (bytes_count / total) * 100 if total > 0 else 0
            lines.append(f"| {lang} | {pct:.1f}% |")
        lines.append("")

    # Roadmap
    lines.extend([
        "##  Learning Roadmap",
        "",
    ])
    for i, step in enumerate(roadmap, 1):
        lines.append(f"{i}. {step}")
    lines.append("")

    # Contribution advice
    lines.extend([
        "##  Contribution Advice",
        "",
    ])
    for tip in advice_list:
        lines.append(f"- {tip}")
    lines.append("")

    lines.extend([
        "---",
        "",
        "*Generated by GitHub Learning Assistant v2.0*",
    ])

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return str(filepath)
    except OSError:
        return None
